apiVersion: v1
kind: Service
metadata:
  name: {{ include "netwatch.fullname" . }}-frontend
  labels:
    component: frontend
    {{- include "netwatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "netwatch.fullname" . }}-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
