apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netwatch.fullname" . }}-secrets
  labels:
    {{- include "netwatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  CAPTURE_TOKEN: {{ .Values.secrets.captureToken | quote }}
  ABUSEIPDB_API_KEY: {{ .Values.secrets.abuseIpDbApiKey | quote }}
